In [1]:
import pandas as pd

pd.set_option('display.max_columns', 500)

In [2]:
df = pd.read_excel('data/GRD Mark Verification by Teacher - Sample.xlsx')

In [3]:
df

,Badge Num,Course,Course Title,Section ID,TermCode,Period,Teacher,StaffGU,Abs1,Abs2,Cit,Con,Credit,SIS Number,Student Name,WH,Quarter Mark,Comment1,Comment2,Comment3
0,NaN,22003R101,AVID 9,22003R101-00005,S1,1,"Babson, Max",701BD9D3-353E-48F9-8A44-741FA88B770E,NaN,NaN,-,-,0,AA71818,"Last, First MI.",-,A+,NaN,NaN,NaN
1,NaN,05155R101,Art 1,05155R101-00006,S1,2,"Friedland, Mara L.",43610AF8-1440-4424-A539-03B1C93B4135,NaN,NaN,-,-,0,AA71818,"Last, First MI.",-,A+,NaN,NaN,NaN
2,NaN,02061R101,Integrated Math 1,02061R101-00001,S1,3,"Barker, Beth K.",09D662A5-D6E2-49DF-ABE5-B6DDB5CE964A,NaN,NaN,-,-,0,AA71818,"Last, First MI.",-,A,NaN,NaN,NaN
3,NaN,05162R000,Exploring Graphic Design,05162R000-00006,S1,4,"Abbert, Carson H.",E6100E15-10AF-45AD-A146-2EE35C2A3C54,NaN,NaN,-,-,0,AA71818,"Last, First MI.",-,A+,NaN,NaN,NaN
4,NaN,08001R100,Physical Education 9,08001R100-00013,S1,5,"Reader, Bailey E.",43B6851A-6446-4480-8074-E6AC281AA8A1,NaN,NaN,-,-,0,AA71818,"Last, First MI.",-,A,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17329,NaN,21006R110,RC/Drone Manufacturing,21006R110-00001,S1,3,"McClellan, Michael S.",15166495-A158-426E-8202-183B3AEDB9BF,NaN,NaN,-,-,0,ZW71404,"Last, First MI.",-,A+,NaN,NaN,NaN
17330,NaN,05167R101,Photography 1,05167R101-00001,S1,4,"Schweinfurth, William",27250D92-5031-453C-82F2-08AA3BF9C2BF,NaN,NaN,-,O - Outstanding,0,ZW71404,"Last, First MI.",O - Outstanding,A,NaN,NaN,NaN
17331,NaN,02061R201,Integrated Math 2,02061R301-00004,S1,5,"Keopraseuth, Antony",F30AD2B0-DE2A-4452-82CE-1BED5DDEBFDD,NaN,NaN,-,-,0,ZW71404,"Last, First MI.",-,C+,NaN,NaN,NaN
17332,NaN,13202R000,Exploring Metals Manufacturing,13202R000-00003,S1,6,"Gutfleisch, Timothy G.",1A2EEE7B-4354-4C97-A4A2-D092A1FE7CAC,NaN,NaN,-,-,0,ZW71404,"Last, First MI.",-,A+,NaN,NaN,NaN
17333,NaN,03201R111,Honors Integrated Science 9,03201R111-00001,S1,7,"Reaney, Tadd",3A95702A-028B-4E66-9169-ED84BEF5819F,NaN,NaN,-,-,0,ZW71404,"Last, First MI.",-,B-,NaN,NaN,NaN

In [8]:
columns = ['SIS Number', 'Student Name', 'TermCode',
           'Period 1', 'Teacher 1', 'Course 1', 'Course Title 1', 'Grading Period Mark 1', 'Abs1 1', 'Abs2 1',
           'Period 2', 'Teacher 2', 'Course 2', 'Course Title 2', 'Grading Period Mark 2', 'Abs1 2', 'Abs2 2',
           'Period 3', 'Teacher 3', 'Course 3', 'Course Title 3', 'Grading Period Mark 3', 'Abs1 3', 'Abs2 3',
           'Period 4', 'Teacher 4', 'Course 4', 'Course Title 4', 'Grading Period Mark 4', 'Abs1 4', 'Abs2 4',
           'Period 5', 'Teacher 5', 'Course 5', 'Course Title 5', 'Grading Period Mark 5', 'Abs1 5', 'Abs2 5',
           'Period 6', 'Teacher 6', 'Course 6', 'Course Title 6', 'Grading Period Mark 6', 'Abs1 6', 'Abs2 6',
           'Period 7', 'Teacher 7', 'Course 7', 'Course Title 7', 'Grading Period Mark 7', 'Abs1 7', 'Abs2 7',
           'Period 8', 'Teacher 8', 'Course 8', 'Course Title 8', 'Grading Period Mark 8', 'Abs1 8', 'Abs2 8',
           'Period 9', 'Teacher 9', 'Course 9', 'Course Title 9', 'Grading Period Mark 9', 'Abs1 9', 'Abs2 9',
           'Period 10', 'Teacher 10', 'Course 10', 'Course Title 10', 'Grading Period Mark 10', 'Abs1 10', 'Abs2 10']

df_modified = pd.DataFrame(columns=columns)

sis_number = df.loc[:, 'SIS Number'][0]

new_row = {'SIS Number':sis_number, 'Student Name':df.loc[:, 'Student Name'][0], 'TermCode':df.loc[:, 'TermCode'][0]}

for index, row in df.iterrows():    
    if row['SIS Number'] == sis_number:
        period = row['Period']
        new_row[f'Period {period}'] = period
        new_row[f'Teacher {period}'] = row['Teacher']
        new_row[f'Course {period}'] = row['Course']
        new_row[f'Course Title {period}'] = row['Course Title']
        new_row[f'Grading Period Mark {period}'] = row['Quarter Mark']
        new_row[f'Abs1 {period}'] = row['Abs1']
        new_row[f'Abs2 {period}'] = row['Abs2']
    else:
        df_modified = df_modified.append(new_row, ignore_index=True)
        sis_number = row['SIS Number']
        new_row = {'SIS Number':sis_number, 'Student Name':df.loc[:, 'Student Name'][0], 'TermCode':df.loc[:, 'TermCode'][0]}
        period = row['Period']
        new_row[f'Period {period}'] = period
        new_row[f'Teacher {period}'] = row['Teacher']
        new_row[f'Course {period}'] = row['Course']
        new_row[f'Course Title {period}'] = row['Course Title']
        new_row[f'Grading Period Mark {period}'] = row['Quarter Mark']
        new_row[f'Abs1 {period}'] = row['Abs1']
        new_row[f'Abs2 {period}'] = row['Abs2']
        
# df_modified.loc[:, [col for col in df_modified if col.startswith('Abs')]] = df_modified.loc[:, [col for col in df_modified if col.startswith('Abs')]].fillna(0)
df_modified = df_modified.fillna('')

df_modified

,SIS Number,Student Name,TermCode,Period 1,Teacher 1,Course 1,Course Title 1,Grading Period Mark 1,Abs1 1,Abs2 1,Period 2,Teacher 2,Course 2,Course Title 2,Grading Period Mark 2,Abs1 2,Abs2 2,Period 3,Teacher 3,Course 3,Course Title 3,Grading Period Mark 3,Abs1 3,Abs2 3,Period 4,Teacher 4,Course 4,Course Title 4,Grading Period Mark 4,Abs1 4,Abs2 4,Period 5,Teacher 5,Course 5,Course Title 5,Grading Period Mark 5,Abs1 5,Abs2 5,Period 6,Teacher 6,Course 6,Course Title 6,Grading Period Mark 6,Abs1 6,Abs2 6,Period 7,Teacher 7,Course 7,Course Title 7,Grading Period Mark 7,Abs1 7,Abs2 7,Period 8,Teacher 8,Course 8,Course Title 8,Grading Period Mark 8,Abs1 8,Abs2 8,Period 9,Teacher 9,Course 9,Course Title 9,Grading Period Mark 9,Abs1 9,Abs2 9,Period 10,Teacher 10,Course 10,Course Title 10,Grading Period Mark 10,Abs1 10,Abs2 10
0,AA71818,"Last, First MI.",S1,1,"Babson, Max",22003R101,AVID 9,A+,,,2,"Friedland, Mara L.",05155R101,Art 1,A+,,,3,"Barker, Beth K.",02061R101,Integrated Math 1,A,,,4,"Abbert, Carson H.",05162R000,Exploring Graphic Design,A+,,,5,"Reader, Bailey E.",08001R100,Physical Education 9,A,,,6,"Needler, Seth",03201R101,Integrated Science 9,B+,,,7,"Johnson, Jenna W.",01001R101,Language Arts 9,A,,,,,,,,,,,,,,,,,,,,,,,
1,AA75072,"Last, First MI.",S1,1,"Ulfers, Kate",04053R101,Modern World History,A+,,,2,"Madzelan, Lisa M.",22003R201,AVID 10,A-,,,3,"Lim, Barbara A.",01002R111,Honors Language Arts 10,A,,,4,"Well, Kyle C.",08051R101,Health 10,A-,,,5,"Kasler, Bailey",22101R201,Student Government,A,,,6,"Keopraseuth, Antony",02061R201,Integrated Math 2,C,,,7,"Morando, MacKenzie",03051R101,Biology,A-,,,,,,,,,,,,,,,,,,,,,,,
2,AA75819,"Last, First MI.",S1,1,"Fuller, Jeffrey D.",22006R101,Credit Recovery,,,,2,"Pageler, Rachel K.",16052R101,Culinary 1: Cooking Fundamentals,B,,,3,"Batt, Theodore T.",02155R101,Financial Algebra,D,,,4,"Robinson-Fischer, Amy",04201R100,Economics,C,,,5,"Gjesdal, Rod J.",05155R101,Art 1,C-,,,6,"Cleys, Jeffrey D.",06103R101,Spanish 3,NP,,,7,"O'Brien, Martin D.",01004R101,Language Arts 12,A,,,,,,,,,,,,,,,,,,,,,,,
3,AA76537,"Last, First MI.",S1,1,"L'Hommedieu, Katherine P.",01008R251,ELD Early Intermediate 1,C-,,,2,"Ulfers, Kate",04053R131,Modern World History S,A-,,,3,"Friedland, Mara L.",05155R101,Art 1,NP,,,4,"Bullock, Sarah E.",01103R231,Language Arts 2 S,B,,,5,"Moffat, Eric R.",03201R131,Integrated Science 9 S,NP,,,6,"Rutherford, Jacqueline",02061R031,Integrated Math S 1 A,D-,,,7,"L'Hommedieu, Katherine P.",01066R231,Reading 2 S,NP,,,,,,,,,,,,,,,,,,,,,,,
4,AAA65040,"Last, First MI.",S1,1,"Lim, Barbara A.",22003R301,AVID 11,A,,,2,"Abbert, Carson H.",05162R201,Graphic Arts 2: Passion/Power/Product,B,,,3,"Savage, Sarah",02061R501,Integrated Math 3,D,,,4,"Needler, Seth",03207R111,AP Environmental Science,NP,,,5,"Kottler, Marc S.",01003R101,Language Arts 11,A,,,6,"Murphy, Kelly M.",08003R100,Competitive Games,B,,,7,"Runckel, Samuel",04053R101,Modern World History,A,,,,,,,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2609,ZST76562,"Last, First MI.",S1,1,"Well, Kyle C.",08051R101,Health 10,NP,,,2,"L'Hommedieu, Katherine P.",01008R251,ELD Early Intermediate 1,A-,,,3,"L'Hommedieu, Katherine P.",01066R231,Reading 2 S,D+,,,4,"Rutherford, Jacqueline",02061R031,Integrated Math S 1 A,C,,,5,"Bullock, Sarah E.",01103R231,Language Arts 2 S,B,,,6,"Ulfers, Kate",04053R131,Modern World History S,A,,,7,"Moffat, Eric R.",03201R131,Integrated Science 9 S,B-,,,,,,,,,,,,,,,,,,,,,,,
2610,ZT65745,"Last, First MI.",S1,1,"McClellan, Michael S.",02152R101,CTE Math,D,,,2,"Aldred, Ryan M.",08009R100,Weight Training,D+,,,3,"Gutfleisch, Timothy G.",13202R201,Metals Manufacturing 2,D-,,,4,"Reaney, Tadd",03159R101,Applied Physical Science,B,,,5,"McJunkin, Noel P.",04103R101,US History,NP,,,6,"McClellan, Michael S.",21006R101,Engineering 1,C-,,,7,"Vella, Jesse F.",01003R101,Language Arts 11,NP,,,,,,,,,,,,,,,,,,,,,,,
2611,ZTM65387,"Last, First MI.",S1,1,"Batt, Theodore T.",02061R401,Integrated Math 2 B,NP,,,2,"Pageler, Rachel K.",16052R101,Culinary 1: Cooking Fundamentals,NP,,,3,"Champney, Natasha T.",01003R101,Language Arts 11,D,,,4,"Kasler, Bailey",22101R101,Student Leadership,C,,,5,"Fuller, Jeffrey D.",22006R101,Credit Recovery,,,,6,"Radford, David R.",03004R100,Sci. Seminar: Astronomy,NP,,,7,"Safko, Karl H.",04103R101,US History,NP,,,,,,,,,,,,,,,,,,,,,,,
2612,ZVD61861,"Last, First MI.",S1,1,"Aldred, Ryan M.",08009R100,Weight Training,A+,,,2,"Miles, Barry L.",04201R100,Economics,A+,,,3,"O'Brien, Martin D.",01004R101,Language Arts 12,A+,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2613,ZVK76015,"Last, First MI.",S1,1,"Chantiny, Erik J.",02061R101,Integrated Math 1,NP,,,2,"Kottler, Marc S.",01001R101,Language Arts 9,D+,,,3,"Walker, Benjamin T.",22102R101,9th Grade Access,B,,,4,"Friedland, Mara L.",05155R101,Art 1,A-,,,5,"Malone, Patrick D.",03201R101,Integrated Science 9,NP,,,6,"Steenson, Laura R.",05056R101,Production Stagecraft,D,,,7,"Murphy, Kelly M.",08001R100,Physical Education 9,NP,,,,,,,,,,,,,,,,,,,,,,,

In [9]:
df_modified.to_csv('compressed_rows.csv')